INSERT INTO groups (group_name) values ('YS-27');
INSERT INTO groups (group_name) values ('HV-14');
INSERT INTO groups (group_name) values ('QM-09');
INSERT INTO groups (group_name) values ('ZF-83');
INSERT INTO groups (group_name) values ('RG-52');
INSERT INTO groups (group_name) values ('PL-41');
INSERT INTO groups (group_name) values ('KX-76');
INSERT INTO groups (group_name) values ('ND-98');
INSERT INTO groups (group_name) values ('TC-63');
INSERT INTO groups (group_name) values ('WU-48');
INSERT INTO groups (group_name) values ('Students without group');

INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Robinson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Thompson', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Clark', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Martinez', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Miller', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Lee', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Hall', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Smith', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Thomas', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Garcia', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Garcia', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Smith', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Robinson', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Thomas', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Rodriguez', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Martinez', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Rodriguez', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Lee', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Taylor', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Thompson', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Williams', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Lewis', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Thompson', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Jones', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Thomas', 6);