INSERT INTO courses (course_name, course_description) values ('Principles of Economics', 'Learn about the fundamentals of economics');
INSERT INTO courses (course_name, course_description) values ('World History: Ancient Civilizations', 'Explore the history of ancient civilizations');
INSERT INTO courses (course_name, course_description) values ('Creative Writing Workshop', 'Develop your writing skills in a creative environment');
INSERT INTO courses (course_name, course_description) values ('Introduction to Psychology', 'Learn the basics of psychology');
INSERT INTO courses (course_name, course_description) values ('Business Ethics and Social Responsibility', 'Explore ethical issues in business and the role of social responsibility');
INSERT INTO courses (course_name, course_description) values ('Human Anatomy and Physiology', 'Study the human body and its functions');
INSERT INTO courses (course_name, course_description) values ('Principles of Marketing', 'Learn the basics of marketing');
INSERT INTO courses (course_name, course_description) values ('Environmental Science and Sustainability', 'Study the science of the environment and explore issues of sustainability');
INSERT INTO courses (course_name, course_description) values ('Fundamentals of Graphic Design', 'Learn the basics of graphic design');
INSERT INTO courses (course_name, course_description) values ('Introduction to Computer Science', 'An introduction to computer science principles and programming');

INSERT INTO groups (group_name) values ('YS-27');
INSERT INTO groups (group_name) values ('HV-14');
INSERT INTO groups (group_name) values ('QM-09');
INSERT INTO groups (group_name) values ('ZF-83');
INSERT INTO groups (group_name) values ('RG-52');
INSERT INTO groups (group_name) values ('PL-41');
INSERT INTO groups (group_name) values ('KX-76');
INSERT INTO groups (group_name) values ('ND-98');
INSERT INTO groups (group_name) values ('TC-63');
INSERT INTO groups (group_name) values ('WU-48');
INSERT INTO groups (group_name) values ('Students without group');

INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Robinson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Thompson', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Clark', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Martinez', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Miller', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Lee', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Hall', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Smith', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Thomas', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Garcia', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Garcia', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Smith', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Robinson', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Thomas', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Rodriguez', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Martinez', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Rodriguez', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Lee', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Taylor', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Thompson', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Williams', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Lewis', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Thompson', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Jones', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Thomas', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Brown', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Rodriguez', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Smith', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Lee', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Clark', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Hall', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Garcia', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Garcia', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Miller', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Jones', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Taylor', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Rodriguez', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Williams', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Williams', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Martinez', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Anderson', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Davis', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Anderson', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Taylor', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Lee', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Garcia', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Robinson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Rodriguez', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Clark', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Robinson', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Thompson', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Smith', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Hall', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Brown', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Brown', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Robinson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Clark', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Johnson', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Thompson', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Johnson', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Smith', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Hall', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Thompson', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Clark', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Smith', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Clark', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Garcia', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Johnson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Thompson', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Robinson', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Wilson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Clark', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Robinson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Miller', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Thomas', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Robinson', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Taylor', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Clark', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Thomas', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Garcia', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Wilson', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Lewis', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Davis', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Rodriguez', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Williams', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Hall', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Jones', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Brown', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Wilson', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Johnson', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Robinson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Robinson', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Brown', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Jones', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Anderson', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Miller', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Lee', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Johnson', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Rodriguez', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Johnson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Miller', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Jones', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Smith', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Hall', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Thompson', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Davis', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Martinez', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Martinez', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Rodriguez', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Rodriguez', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Anderson', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Lee', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Martinez', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Rodriguez', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Taylor', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Williams', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Anderson', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Hall', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Brown', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Clark', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Davis', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Lee', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Taylor', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Rodriguez', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Wilson', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Davis', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Thomas', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Johnson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Thompson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Jones', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Anderson', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Olivia', 'Jones', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Miller', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Lee', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Jones', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Robinson', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Thomas', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Miller', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Anderson', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Miller', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Noah', 'Davis', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Hall', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Thompson', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Robinson', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Rodriguez', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Miller', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Lee', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Wilson', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Smith', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Lewis', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Lewis', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Thompson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Davis', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Jones', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Jones', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Oliver', 'Smith', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Thompson', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Smith', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Smith', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Lewis', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Rodriguez', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Davis', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Rodriguez', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Lewis', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Ava', 'Garcia', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Taylor', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Taylor', 1);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Clark', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Martinez', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Lewis', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Isabella', 'Martinez', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Harper', 'Taylor', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Elijah', 'Taylor', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Williams', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Aiden', 'Smith', 3);
INSERT INTO students (first_name, last_name, group_id) values ('Liam', 'Wilson', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Williams', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Davis', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Rodriguez', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Lucas', 'Garcia', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Grayson', 'Lee', 7);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Johnson', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Abigail', 'Martinez', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Williams', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Jackson', 'Lee', 4);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Garcia', 8);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Williams', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Sophia', 'Taylor', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Emma', 'Garcia', 11);
INSERT INTO students (first_name, last_name, group_id) values ('Evelyn', 'Anderson', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Amelia', 'Williams', 2);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Anderson', 9);
INSERT INTO students (first_name, last_name, group_id) values ('Carter', 'Davis', 10);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Williams', 6);
INSERT INTO students (first_name, last_name, group_id) values ('Caden', 'Miller', 5);
INSERT INTO students (first_name, last_name, group_id) values ('Mia', 'Thomas', 8);

INSERT INTO studenttocourse (student_id, course_id) values (117, 9);
INSERT INTO studenttocourse (student_id, course_id) values (154, 2);
INSERT INTO studenttocourse (student_id, course_id) values (154, 8);
INSERT INTO studenttocourse (student_id, course_id) values (154, 10);
INSERT INTO studenttocourse (student_id, course_id) values (35, 1);
INSERT INTO studenttocourse (student_id, course_id) values (35, 5);
INSERT INTO studenttocourse (student_id, course_id) values (27, 1);
INSERT INTO studenttocourse (student_id, course_id) values (27, 4);
INSERT INTO studenttocourse (student_id, course_id) values (27, 10);
INSERT INTO studenttocourse (student_id, course_id) values (120, 2);
INSERT INTO studenttocourse (student_id, course_id) values (120, 7);
INSERT INTO studenttocourse (student_id, course_id) values (120, 8);
INSERT INTO studenttocourse (student_id, course_id) values (170, 2);
INSERT INTO studenttocourse (student_id, course_id) values (148, 8);
INSERT INTO studenttocourse (student_id, course_id) values (68, 2);
INSERT INTO studenttocourse (student_id, course_id) values (68, 5);
INSERT INTO studenttocourse (student_id, course_id) values (68, 8);
INSERT INTO studenttocourse (student_id, course_id) values (109, 5);
INSERT INTO studenttocourse (student_id, course_id) values (109, 10);
INSERT INTO studenttocourse (student_id, course_id) values (29, 10);
INSERT INTO studenttocourse (student_id, course_id) values (181, 7);
INSERT INTO studenttocourse (student_id, course_id) values (197, 2);
INSERT INTO studenttocourse (student_id, course_id) values (197, 9);
INSERT INTO studenttocourse (student_id, course_id) values (140, 2);
INSERT INTO studenttocourse (student_id, course_id) values (140, 6);
INSERT INTO studenttocourse (student_id, course_id) values (140, 10);
INSERT INTO studenttocourse (student_id, course_id) values (161, 7);
INSERT INTO studenttocourse (student_id, course_id) values (161, 8);
INSERT INTO studenttocourse (student_id, course_id) values (196, 1);
INSERT INTO studenttocourse (student_id, course_id) values (196, 6);
INSERT INTO studenttocourse (student_id, course_id) values (196, 8);
INSERT INTO studenttocourse (student_id, course_id) values (166, 6);
INSERT INTO studenttocourse (student_id, course_id) values (166, 7);
INSERT INTO studenttocourse (student_id, course_id) values (101, 1);
INSERT INTO studenttocourse (student_id, course_id) values (101, 3);
INSERT INTO studenttocourse (student_id, course_id) values (101, 7);
INSERT INTO studenttocourse (student_id, course_id) values (91, 5);
INSERT INTO studenttocourse (student_id, course_id) values (167, 1);
INSERT INTO studenttocourse (student_id, course_id) values (167, 8);
INSERT INTO studenttocourse (student_id, course_id) values (167, 9);
INSERT INTO studenttocourse (student_id, course_id) values (105, 9);
INSERT INTO studenttocourse (student_id, course_id) values (85, 1);
INSERT INTO studenttocourse (student_id, course_id) values (85, 4);
INSERT INTO studenttocourse (student_id, course_id) values (85, 6);
INSERT INTO studenttocourse (student_id, course_id) values (186, 6);
INSERT INTO studenttocourse (student_id, course_id) values (40, 1);
INSERT INTO studenttocourse (student_id, course_id) values (40, 7);
INSERT INTO studenttocourse (student_id, course_id) values (40, 8);
INSERT INTO studenttocourse (student_id, course_id) values (137, 9);
INSERT INTO studenttocourse (student_id, course_id) values (84, 5);
INSERT INTO studenttocourse (student_id, course_id) values (84, 9);
INSERT INTO studenttocourse (student_id, course_id) values (135, 1);
INSERT INTO studenttocourse (student_id, course_id) values (135, 3);
INSERT INTO studenttocourse (student_id, course_id) values (135, 7);
INSERT INTO studenttocourse (student_id, course_id) values (31, 9);
INSERT INTO studenttocourse (student_id, course_id) values (13, 5);
INSERT INTO studenttocourse (student_id, course_id) values (34, 1);
INSERT INTO studenttocourse (student_id, course_id) values (34, 8);
INSERT INTO studenttocourse (student_id, course_id) values (49, 4);
INSERT INTO studenttocourse (student_id, course_id) values (129, 2);
INSERT INTO studenttocourse (student_id, course_id) values (129, 5);
INSERT INTO studenttocourse (student_id, course_id) values (87, 5);
INSERT INTO studenttocourse (student_id, course_id) values (80, 3);
INSERT INTO studenttocourse (student_id, course_id) values (80, 5);
INSERT INTO studenttocourse (student_id, course_id) values (36, 10);
INSERT INTO studenttocourse (student_id, course_id) values (156, 1);
INSERT INTO studenttocourse (student_id, course_id) values (156, 4);
INSERT INTO studenttocourse (student_id, course_id) values (114, 2);
INSERT INTO studenttocourse (student_id, course_id) values (114, 5);
INSERT INTO studenttocourse (student_id, course_id) values (74, 7);
INSERT INTO studenttocourse (student_id, course_id) values (66, 5);
INSERT INTO studenttocourse (student_id, course_id) values (30, 3);
INSERT INTO studenttocourse (student_id, course_id) values (30, 10);
INSERT INTO studenttocourse (student_id, course_id) values (32, 5);
INSERT INTO studenttocourse (student_id, course_id) values (102, 9);
INSERT INTO studenttocourse (student_id, course_id) values (115, 9);
INSERT INTO studenttocourse (student_id, course_id) values (119, 9);
INSERT INTO studenttocourse (student_id, course_id) values (164, 7);
INSERT INTO studenttocourse (student_id, course_id) values (63, 1);
INSERT INTO studenttocourse (student_id, course_id) values (63, 2);
INSERT INTO studenttocourse (student_id, course_id) values (63, 7);
INSERT INTO studenttocourse (student_id, course_id) values (118, 2);
INSERT INTO studenttocourse (student_id, course_id) values (118, 6);
INSERT INTO studenttocourse (student_id, course_id) values (150, 3);
INSERT INTO studenttocourse (student_id, course_id) values (150, 4);
INSERT INTO studenttocourse (student_id, course_id) values (150, 9);
INSERT INTO studenttocourse (student_id, course_id) values (200, 1);
INSERT INTO studenttocourse (student_id, course_id) values (200, 6);
INSERT INTO studenttocourse (student_id, course_id) values (192, 10);
INSERT INTO studenttocourse (student_id, course_id) values (1, 7);
INSERT INTO studenttocourse (student_id, course_id) values (44, 10);
INSERT INTO studenttocourse (student_id, course_id) values (56, 4);
INSERT INTO studenttocourse (student_id, course_id) values (56, 10);
INSERT INTO studenttocourse (student_id, course_id) values (127, 7);
INSERT INTO studenttocourse (student_id, course_id) values (127, 9);
INSERT INTO studenttocourse (student_id, course_id) values (195, 3);
INSERT INTO studenttocourse (student_id, course_id) values (195, 10);
INSERT INTO studenttocourse (student_id, course_id) values (81, 9);
INSERT INTO studenttocourse (student_id, course_id) values (7, 5);
INSERT INTO studenttocourse (student_id, course_id) values (7, 8);
INSERT INTO studenttocourse (student_id, course_id) values (151, 3);
INSERT INTO studenttocourse (student_id, course_id) values (151, 5);
INSERT INTO studenttocourse (student_id, course_id) values (151, 8);
INSERT INTO studenttocourse (student_id, course_id) values (149, 8);
INSERT INTO studenttocourse (student_id, course_id) values (172, 9);
INSERT INTO studenttocourse (student_id, course_id) values (95, 4);
INSERT INTO studenttocourse (student_id, course_id) values (95, 6);
INSERT INTO studenttocourse (student_id, course_id) values (95, 10);
INSERT INTO studenttocourse (student_id, course_id) values (159, 1);
INSERT INTO studenttocourse (student_id, course_id) values (159, 7);
INSERT INTO studenttocourse (student_id, course_id) values (159, 9);
INSERT INTO studenttocourse (student_id, course_id) values (42, 5);
INSERT INTO studenttocourse (student_id, course_id) values (42, 8);
INSERT INTO studenttocourse (student_id, course_id) values (42, 9);
INSERT INTO studenttocourse (student_id, course_id) values (126, 1);
INSERT INTO studenttocourse (student_id, course_id) values (165, 3);
INSERT INTO studenttocourse (student_id, course_id) values (165, 8);
INSERT INTO studenttocourse (student_id, course_id) values (33, 2);
INSERT INTO studenttocourse (student_id, course_id) values (33, 3);
INSERT INTO studenttocourse (student_id, course_id) values (33, 5);
INSERT INTO studenttocourse (student_id, course_id) values (198, 6);
INSERT INTO studenttocourse (student_id, course_id) values (158, 1);
INSERT INTO studenttocourse (student_id, course_id) values (158, 3);
INSERT INTO studenttocourse (student_id, course_id) values (158, 9);
INSERT INTO studenttocourse (student_id, course_id) values (58, 5);
INSERT INTO studenttocourse (student_id, course_id) values (58, 6);
INSERT INTO studenttocourse (student_id, course_id) values (58, 10);
INSERT INTO studenttocourse (student_id, course_id) values (128, 3);
INSERT INTO studenttocourse (student_id, course_id) values (28, 2);
INSERT INTO studenttocourse (student_id, course_id) values (28, 3);
INSERT INTO studenttocourse (student_id, course_id) values (15, 1);
INSERT INTO studenttocourse (student_id, course_id) values (15, 7);
INSERT INTO studenttocourse (student_id, course_id) values (15, 10);
INSERT INTO studenttocourse (student_id, course_id) values (16, 1);
INSERT INTO studenttocourse (student_id, course_id) values (16, 4);
INSERT INTO studenttocourse (student_id, course_id) values (124, 3);
INSERT INTO studenttocourse (student_id, course_id) values (2, 1);
INSERT INTO studenttocourse (student_id, course_id) values (2, 6);
INSERT INTO studenttocourse (student_id, course_id) values (2, 7);
INSERT INTO studenttocourse (student_id, course_id) values (57, 5);
INSERT INTO studenttocourse (student_id, course_id) values (57, 8);
INSERT INTO studenttocourse (student_id, course_id) values (199, 1);
INSERT INTO studenttocourse (student_id, course_id) values (199, 3);
INSERT INTO studenttocourse (student_id, course_id) values (176, 2);
INSERT INTO studenttocourse (student_id, course_id) values (176, 9);
INSERT INTO studenttocourse (student_id, course_id) values (43, 2);
INSERT INTO studenttocourse (student_id, course_id) values (43, 4);
INSERT INTO studenttocourse (student_id, course_id) values (45, 8);
INSERT INTO studenttocourse (student_id, course_id) values (45, 9);
INSERT INTO studenttocourse (student_id, course_id) values (12, 5);
INSERT INTO studenttocourse (student_id, course_id) values (12, 6);
INSERT INTO studenttocourse (student_id, course_id) values (12, 8);
INSERT INTO studenttocourse (student_id, course_id) values (39, 1);
INSERT INTO studenttocourse (student_id, course_id) values (39, 3);
INSERT INTO studenttocourse (student_id, course_id) values (39, 8);
INSERT INTO studenttocourse (student_id, course_id) values (133, 8);
INSERT INTO studenttocourse (student_id, course_id) values (41, 6);
INSERT INTO studenttocourse (student_id, course_id) values (113, 3);
INSERT INTO studenttocourse (student_id, course_id) values (113, 5);
INSERT INTO studenttocourse (student_id, course_id) values (69, 3);
INSERT INTO studenttocourse (student_id, course_id) values (69, 9);
INSERT INTO studenttocourse (student_id, course_id) values (70, 3);
INSERT INTO studenttocourse (student_id, course_id) values (70, 6);
INSERT INTO studenttocourse (student_id, course_id) values (70, 10);
INSERT INTO studenttocourse (student_id, course_id) values (6, 9);
INSERT INTO studenttocourse (student_id, course_id) values (92, 2);
INSERT INTO studenttocourse (student_id, course_id) values (92, 4);
INSERT INTO studenttocourse (student_id, course_id) values (92, 10);
INSERT INTO studenttocourse (student_id, course_id) values (4, 3);
INSERT INTO studenttocourse (student_id, course_id) values (4, 10);
INSERT INTO studenttocourse (student_id, course_id) values (123, 3);
INSERT INTO studenttocourse (student_id, course_id) values (5, 1);
INSERT INTO studenttocourse (student_id, course_id) values (5, 3);
INSERT INTO studenttocourse (student_id, course_id) values (5, 6);
INSERT INTO studenttocourse (student_id, course_id) values (94, 3);
INSERT INTO studenttocourse (student_id, course_id) values (94, 8);
INSERT INTO studenttocourse (student_id, course_id) values (100, 2);
INSERT INTO studenttocourse (student_id, course_id) values (100, 5);
INSERT INTO studenttocourse (student_id, course_id) values (100, 7);
INSERT INTO studenttocourse (student_id, course_id) values (48, 2);
INSERT INTO studenttocourse (student_id, course_id) values (48, 5);
INSERT INTO studenttocourse (student_id, course_id) values (48, 7);
INSERT INTO studenttocourse (student_id, course_id) values (88, 2);
INSERT INTO studenttocourse (student_id, course_id) values (175, 6);
INSERT INTO studenttocourse (student_id, course_id) values (175, 7);
INSERT INTO studenttocourse (student_id, course_id) values (138, 1);
INSERT INTO studenttocourse (student_id, course_id) values (138, 2);
INSERT INTO studenttocourse (student_id, course_id) values (138, 5);
INSERT INTO studenttocourse (student_id, course_id) values (111, 5);
INSERT INTO studenttocourse (student_id, course_id) values (131, 3);
INSERT INTO studenttocourse (student_id, course_id) values (86, 1);
INSERT INTO studenttocourse (student_id, course_id) values (86, 5);
INSERT INTO studenttocourse (student_id, course_id) values (86, 10);
INSERT INTO studenttocourse (student_id, course_id) values (64, 3);
INSERT INTO studenttocourse (student_id, course_id) values (64, 4);
INSERT INTO studenttocourse (student_id, course_id) values (64, 7);
INSERT INTO studenttocourse (student_id, course_id) values (130, 3);
INSERT INTO studenttocourse (student_id, course_id) values (130, 4);
INSERT INTO studenttocourse (student_id, course_id) values (130, 8);
INSERT INTO studenttocourse (student_id, course_id) values (53, 8);
INSERT INTO studenttocourse (student_id, course_id) values (76, 3);
INSERT INTO studenttocourse (student_id, course_id) values (76, 9);
INSERT INTO studenttocourse (student_id, course_id) values (162, 7);
INSERT INTO studenttocourse (student_id, course_id) values (162, 9);
INSERT INTO studenttocourse (student_id, course_id) values (75, 3);
INSERT INTO studenttocourse (student_id, course_id) values (75, 10);
INSERT INTO studenttocourse (student_id, course_id) values (177, 8);
INSERT INTO studenttocourse (student_id, course_id) values (132, 3);
INSERT INTO studenttocourse (student_id, course_id) values (132, 5);
INSERT INTO studenttocourse (student_id, course_id) values (132, 8);
INSERT INTO studenttocourse (student_id, course_id) values (157, 1);
INSERT INTO studenttocourse (student_id, course_id) values (157, 3);
INSERT INTO studenttocourse (student_id, course_id) values (157, 5);
INSERT INTO studenttocourse (student_id, course_id) values (190, 3);
INSERT INTO studenttocourse (student_id, course_id) values (190, 10);
INSERT INTO studenttocourse (student_id, course_id) values (188, 4);
INSERT INTO studenttocourse (student_id, course_id) values (188, 5);
INSERT INTO studenttocourse (student_id, course_id) values (188, 10);
INSERT INTO studenttocourse (student_id, course_id) values (54, 10);
INSERT INTO studenttocourse (student_id, course_id) values (121, 7);
INSERT INTO studenttocourse (student_id, course_id) values (10, 6);
INSERT INTO studenttocourse (student_id, course_id) values (180, 8);
INSERT INTO studenttocourse (student_id, course_id) values (163, 4);
INSERT INTO studenttocourse (student_id, course_id) values (163, 5);
INSERT INTO studenttocourse (student_id, course_id) values (163, 8);
INSERT INTO studenttocourse (student_id, course_id) values (194, 5);
INSERT INTO studenttocourse (student_id, course_id) values (194, 8);
INSERT INTO studenttocourse (student_id, course_id) values (194, 10);
INSERT INTO studenttocourse (student_id, course_id) values (96, 1);
INSERT INTO studenttocourse (student_id, course_id) values (96, 7);
INSERT INTO studenttocourse (student_id, course_id) values (169, 4);
INSERT INTO studenttocourse (student_id, course_id) values (169, 8);
INSERT INTO studenttocourse (student_id, course_id) values (169, 9);
INSERT INTO studenttocourse (student_id, course_id) values (25, 5);
INSERT INTO studenttocourse (student_id, course_id) values (25, 6);
INSERT INTO studenttocourse (student_id, course_id) values (18, 4);
INSERT INTO studenttocourse (student_id, course_id) values (18, 5);
INSERT INTO studenttocourse (student_id, course_id) values (18, 8);
INSERT INTO studenttocourse (student_id, course_id) values (160, 5);
INSERT INTO studenttocourse (student_id, course_id) values (160, 10);
INSERT INTO studenttocourse (student_id, course_id) values (37, 4);
INSERT INTO studenttocourse (student_id, course_id) values (37, 5);
INSERT INTO studenttocourse (student_id, course_id) values (22, 7);
INSERT INTO studenttocourse (student_id, course_id) values (24, 5);
INSERT INTO studenttocourse (student_id, course_id) values (52, 2);
INSERT INTO studenttocourse (student_id, course_id) values (78, 4);
INSERT INTO studenttocourse (student_id, course_id) values (173, 4);
INSERT INTO studenttocourse (student_id, course_id) values (11, 3);
INSERT INTO studenttocourse (student_id, course_id) values (11, 5);
INSERT INTO studenttocourse (student_id, course_id) values (11, 7);
INSERT INTO studenttocourse (student_id, course_id) values (152, 9);
INSERT INTO studenttocourse (student_id, course_id) values (38, 7);
INSERT INTO studenttocourse (student_id, course_id) values (72, 4);
INSERT INTO studenttocourse (student_id, course_id) values (116, 2);
INSERT INTO studenttocourse (student_id, course_id) values (116, 6);
INSERT INTO studenttocourse (student_id, course_id) values (116, 10);
INSERT INTO studenttocourse (student_id, course_id) values (99, 6);
INSERT INTO studenttocourse (student_id, course_id) values (46, 2);
INSERT INTO studenttocourse (student_id, course_id) values (46, 8);
INSERT INTO studenttocourse (student_id, course_id) values (46, 10);
INSERT INTO studenttocourse (student_id, course_id) values (89, 4);
INSERT INTO studenttocourse (student_id, course_id) values (89, 6);
INSERT INTO studenttocourse (student_id, course_id) values (141, 5);
INSERT INTO studenttocourse (student_id, course_id) values (79, 4);
INSERT INTO studenttocourse (student_id, course_id) values (83, 5);
INSERT INTO studenttocourse (student_id, course_id) values (83, 6);
INSERT INTO studenttocourse (student_id, course_id) values (83, 9);
INSERT INTO studenttocourse (student_id, course_id) values (187, 7);
INSERT INTO studenttocourse (student_id, course_id) values (187, 9);
INSERT INTO studenttocourse (student_id, course_id) values (174, 4);
INSERT INTO studenttocourse (student_id, course_id) values (174, 6);
INSERT INTO studenttocourse (student_id, course_id) values (174, 7);
INSERT INTO studenttocourse (student_id, course_id) values (47, 4);
INSERT INTO studenttocourse (student_id, course_id) values (47, 8);
INSERT INTO studenttocourse (student_id, course_id) values (67, 1);
INSERT INTO studenttocourse (student_id, course_id) values (50, 4);
INSERT INTO studenttocourse (student_id, course_id) values (50, 8);
INSERT INTO studenttocourse (student_id, course_id) values (189, 4);
INSERT INTO studenttocourse (student_id, course_id) values (189, 7);
INSERT INTO studenttocourse (student_id, course_id) values (189, 9);
INSERT INTO studenttocourse (student_id, course_id) values (51, 5);
INSERT INTO studenttocourse (student_id, course_id) values (51, 7);
INSERT INTO studenttocourse (student_id, course_id) values (51, 10);
INSERT INTO studenttocourse (student_id, course_id) values (104, 3);
INSERT INTO studenttocourse (student_id, course_id) values (104, 4);